### PR TITLE
This removes the use of the patch command and replaces it with cmake -E copy

### PR DESCRIPTION
**Pull request by billhoffman**
@RussTedrake 
The files changed by the .diff files were patched on a machine with patch.
Then the files were copied into the patches tree. The patch step was updated
to use cmake -E copy to get those changes into the source tree before the
build.

### CODE REVIEW

**Comment by RussTedrake** [comment]
I worry that this is much more difficult to maintain.  Bullet is under active development, and updating the patch to a new version of bullet is somehow much easier than updating a file (even though it's only a few diff commands apart).

**Comment by billhoffman** [comment]
I thought you might not like this approach... :)   Another option is to maintain a fork like we are doing for LCM and pulling from a git repo that has all the code as is.  I have looked into a cross platform cmake -E patch but there is just no BSD licensed patch program that we can use.

**Comment by RussTedrake** [comment]
Why does this not work?
http://gnuwin32.sourceforge.net/packages/patch.htm
- Russ

**Comment by billhoffman** [comment]
It is another tool that a user would have to install.  Also, it requires windows control line feeds which might cause trouble for users.  The more I think about it, I think a git clone with upstream tracking would be the best solution.

**Comment by RussTedrake** [comment]
They wouldn’t have to install it if we included it in the gtk-pod. Are you sure
line feeds would be a problem?

**Comment by RussTedrake** [comment]
Just noticed that I had this in the windows installation instructions:
To use bullet on windows, you need to install 
[patch](http://gnuwin32.sourceforge.net/packages/patch.htm).  If you're on 
Windows 7, you'll also need to follow the instructions here to run 
patch.exe:  
http://math.nist.gov/oommf/software-patchsets/patch_on_Windows7.html

**Comment by billhoffman** [comment]
Right, but now that bullet is default on, IMO that seems a bit too much to ask.  They should install CMake and a compiler and be ready to go.

**Comment by RussTedrake** [comment]
it's true.  the instructions are ridiculous to an extreme.  if I remember correctly, we could simply rename patch.exe to aka mypatch.exe and get around it?

**Comment by patmarion** [comment]
What do you think about maintaining the patches on a git branch?  That would remove the download and patch steps, and use a git clone instead.

**Comment by billhoffman** [comment]
@patmarion me a few comments back: "The more I think about it, I think a git clone with upstream tracking would be the best solution."  :)

**Comment by sherm1** [comment]
I got bit by this in RobotLocomotion/drake#1789. The instructions I used didn't cover this so it took me a while to notice the problem and figure out the patch to the GNU patch command. Would have been better but still awkward with instructions.

You have probably been through this already but -- why does Bullet have to be patched? Could we ask Erwin to fix this (or submit a PR to him) so we don't need a patch at all?

**Comment by billhoffman** [comment]
My vote right now would be to go ahead and merge this change in, and then create a git fork in the next week or so.  Due to an issue that I just fixed in the Jenkins builds the missing patch step was not being detected.  However, I have fixed that issue, and all Windows builds are going to show up as failed from Jenkins until this gets fixed.

**Comment by RussTedrake** [comment]
ok.  i agree that the best solution is to fork bullet directly and apply our patches to that fork.  then we can completely remove this pod and replace it with that cleaner version.  and/or perhaps even push back upstream.
will merge this now.  @billhoffman -- can you make an issue for the real fix?

**Comment by billhoffman** [comment]
OK, created: https://github.com/RobotLocomotion/drake/issues/1824
I will create a pull request that uses this new hash for now.

**Pull request merged**
